export default defineAppConfig({
  pages: [
    'pages/index/index',
    'pages/quiz/index',
    'pages/report/index',
    'pages/poster/index',
    'pages/learning/index',
    'pages/history/index',
    'pages/history/detail',
    'pages/garden/index',
    'pages/mistakes/index',
    'pages/review/index',
    'pages/monthly-report/index',
    'pages/profile/index',
    'pages/settings/index',
    'pages/knowledge/index',
    'pages/knowledge/document',
    'pages/knowledge/import',
    'pages/knowledge/bank',
    'pages/maintenance/index',
  ],
  window: {
    navigationStyle: 'custom',
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#fffdf5',
    navigationBarTitleText: '竹知岛',
    navigationBarTextStyle: 'black',
  },
  tabBar: {
    custom: process.env.TARO_ENV === 'weapp',
    color: '#89928c',
    selectedColor: '#1f6044',
    backgroundColor: '#fffdf5',
    borderStyle: 'white',
    list: [
      {
        pagePath: 'pages/index/index',
        text: '闯关',
      },
      {
        pagePath: 'pages/learning/index',
        text: '我的',
      },
    ],
  },
  usingComponents: {},
})
